backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads" # Where uploaded media files will go
public_folder: "/images/uploads" # Public path for media files

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "body", label: "Body", widget: "markdown" }
